CREATE TABLE AUTORES (
    AUT_ID INT PRIMARY KEY,
    AUT_NOME VARCHAR(100),
    AUT_PAIS VARCHAR(50)
);

CREATE TABLE LIVROS (
    LIV_ISBN VARCHAR(13) PRIMARY KEY,
    LIV_TITULO VARCHAR(200),
    LIV_ANO INTEGER,
    LIV_AUT_ID INTEGER REFERENCES AUTORES(AUT_ID)
);